# This workflow will test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: fetch packages
      run: |
        go mod download
        go mod verify

    - name: Test
      run: go test -covermode=count -coverprofile=cover.out ./internal/auth ./internal/dto

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: cover.out
        fail_ci_if_error: true

